---
# handlers file for add_check_login_monitoring
 - name: restart the nrpe service on redhat
   service: name=nrpe state=restarted
   when: ansible_os_family == "RedHat"

 - name: restart the nrpe service on ubuntu
   service: name=nagios-nrpe-server state=restarted
   when: ansible_os_family == "Debian"
